### ISSUE TITLE
ssvl3 alert handshake failure

### ISSUE THREAD

**Issue by repat** [davidtsadler/ebay-sdk#12]
Hi,

I know it's technically a problem with *guzzle* (see below) but it seems like after updating our PHP and OpenSSL version, eBay and my server don't have a common way to talk except TLS1.0. I already tried to add `CURLOPT_SSLVERSION => CURL_SSLVERSION_TLSv1_0` in `$curlOptions` in `CurlHandle.php` but it seems the script is trying to use SSLv3. Could you point me in a direction on how to fix this?

```
Requesting job Id from eBay...Done
JobId [5436649543] FileReferenceId [5464013953]
Uploading fixed price item requests...PHP Fatal error:  Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 35: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure [url] https://storage.ebay.com/FileTransferService' in /www/htdocs/username/ebay/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php:359
Stack trace:
#0 /www/htdocs/username/ebay/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(292): Guzzle\Http\Curl\CurlMulti->isCurlException(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#1 /www/htdocs/username/ebay/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#2 /www/htdocs/username/ebay/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(240): Guzzle\Http\Curl\CurlMulti->processMessages()
#3 /www/htdocs/username/ebay/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.ph in /www/htdocs/username/ebay/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php on line 359
```

**Comment by michabbb** [comment]
don´t know if that helps: i am using guzzle version 3.8.1 without any errors... maybe you try this....

**Comment by repat** [comment]
Thanks, that seems to work. I also got another problem with futures when I used guzzle 5.x and ran it from the browser instead of commandline.

**Comment by repat** [comment]
Nope, still get the error randomly :/

**Comment by davidtsadler** [comment]
I've had similar problems connecting to the file transfer service on another project. This was using cURL which is what Guzzle uses. I don't know if it will help but you could try setting `CURLOPT_SSL_CIPHER_LIST => 'RC4-SHA'` in `$curlOptions`. If you get an error about *unknown cipher* try `CURLOPT_SSL_CIPHER_LIST => 'rsa_rc4_128_sha`` instead. Other than that I don't know what else to suggest until I take a more in depth look which could take a while as I'm not all to familiar with the internals of Guzzle.

**Comment by repat** [comment]
In the end I didn't change the SSL Version (as said in my initial post) but forced the cipher list to only one entry, since this seems to be the only version my server and the eBay server had in common.

btw, the last time I checked eBay was still offering RC4, [which is "forbidden" by the IETF](https://tools.ietf.org/html/rfc7465).

```php
CURLOPT_SSL_CIPHER_LIST => 'TLSv1'
```
