### ISSUE TITLE
High number of remote calls

### ISSUE THREAD

**Issue by wriggle** [davidtsadler/ebay-sdk#13]
Hi David,

Thanks for this superb SDK. It makes working with the Ebay API so much easier.

I'm currently profiling the performance of an internal API I've created using your SDK to search Ebay. I'm seeing quite slow response times and, looking into the profiling data, I'm seeing numerous CurlMulti requests sent for just one findItemsAdvanced API call. I've attached a screenshot.

![screen-shot-2015-04-07-at-16 15 09](https://cloud.githubusercontent.com/assets/443147/7026528/1830edbe-dd42-11e4-8566-38d96dc21ff8.jpg)

Is this expected behaviour? Can you point me to where your SDK created the cURL handles?

Thanks,

Matt

**Comment by michabbb** [comment]
hi, which tool are you using ? where does this screenshot come from? looks nice ;)

**Comment by davidtsadler** [comment]
Creation of cURL handles is done by [Guzzle](https://github.com/guzzle/guzzle3). The SDK creates an instance of a Guzzle client which then [handles the request and response](https://github.com/davidtsadler/ebay-sdk/blob/master/src/DTS/eBaySDK/HttpClient/HttpClient.php#L43)

As far as I know the number of times that [curl_multi_select](http://php.net/manual/en/function.curl-multi-select.php) is called is not related to the number of requests actually sent. If you look at how Guzzle [calls the function](https://github.com/guzzle/guzzle3/blob/master/src/Guzzle/Http/Curl/CurlMulti.php#L241) you should see that it is during a loop and so will be called several times for one request.  I think you can see how many requests are made by looking at how many times the method [createCurlHandle](https://github.com/guzzle/guzzle3/blob/master/src/Guzzle/Http/Curl/CurlMulti.php#L192) is called as I believe that is ultimately responsible for creating a curl handle.

**Comment by wriggle** [comment]
Thanks David. That clarifies things. I'll have to keep digging to work out why my requests are taking so long.

For michabbb: the profiler is called Blackfire but, while it looks pretty, it's not very informative and therefore far less useful than PHP Debug.

**Comment by zoransa** [comment]
guzzle recommends update to new version "guzzlehttp/guzzle": "~6.0"
