### ISSUE TITLE
http://devbay.net/sdk/guides/requirements/#issues Suggestion

### ISSUE THREAD

**Issue by jpliew** [davidtsadler/ebay-sdk#14]
Hi David,

Just curious if using string for Id handling for 32bit and 64bit will help in this situation?

Keep up the good work mate.

Cheers
JP

**Comment by davidtsadler** [comment]
This will be implemented in the [Version 1.0 release](https://github.com/davidtsadler/ebay-sdk-php/issues/3) as a new global SDK option will be added that will relax the type checking used when assigning values to properties.
