### ISSUE TITLE
Bulkdataexchange file transfer error

### ISSUE THREAD

**Issue by winni4eva** [davidtsadler/ebay-sdk#16]
Recently uploading files using the File transfer service returns server error. 
$transferService = new FileTransfer\Services\FileTransferService(array(
    'authToken' => $config['sandbox']['userToken'],
    'sandbox' => true
));
$uploadFileResponse = $transferService->uploadFile($uploadFileRequest);

[reason phrase] Internal Server Error
[url] https://storage.sandbox.ebay.com/FileTransferService [] []
[2015-07-16 10:54:31] local.ERROR: Exception caught, filename: vendor/guzzle/guzzle/src/Guzzle/Http/Exception/BadResponseException.php on line: 43 [] []
[2015-07-16 10:54:31] local.INFO: Server error response
[status code] 500
[reason phrase] Internal Server Error
[url] https://storage.sandbox.ebay.com/FileTransferService [] [].

I am not sure if ebay have updated their headers or this is an issue with the sandbox. Thanks for providing us with this sdk, its made working with ebay a breeze.

**Comment by winni4eva** [comment]
I just tested on the production servers, everything worked perfectly, seems to be a sandbox issue.

**Comment by davidtsadler** [comment]
Sadly using the sandbox can leave you doubting your own sanity as you can never be 100% sure if an issue is due to your code or the sandbox. It also looks like there is currently another issue on going https://go.developer.ebay.com/filetransfer-api-throwing-authentication-error-11002-sandbox

**Comment by winni4eva** [comment]
Thanks David, its been a great learning experience using your ebay php
package, you are right the issue was with the sandbox. I now make it a
point to check the ebay api status page
https://go.developer.ebay.com/api-status for any errors with either the
sandbox or production api's any time I have issues. Thanks sooo much for
the package, I would not have gotten this far without it.
