### ISSUE TITLE
Confusion in GetCategoryFeature Response

### ISSUE THREAD

**Issue by raheelkhan** [davidtsadler/ebay-sdk#17]
Hi, Thank you for the awesome SDK.

I was trying to call `AddFixedPriceItemRequestType` with `siteId` = 207 (Malaysia) and was getting a response error 
`The duration "GTC" day(s) is not available for this listing type, or invalid for category "57991"`

Then i called `GetCategoryFeaturesRequestType` to see if it supports `GTC`. And below is the response i get from this call which is unclear to me how to read that.

```
DTS\eBaySDK\Trading\Types\GetCategoryFeaturesResponseType Object
(
    [values:DTS\eBaySDK\Types\BaseType:private] => Array
        (
            [Timestamp] => DateTime Object
                (
                    [date] => 2015-10-09 22:13:24
                    [timezone_type] => 2
                    [timezone] => Z
                )

            [Ack] => Success
            [Version] => 927
            [Build] => E927_INTL_API_17590342_R1
            [CategoryVersion] => 275
            [UpdateTime] => DateTime Object
                (
                    [date] => 2015-10-09 15:48:46
                    [timezone_type] => 2
                    [timezone] => Z
                )

            [FeatureDefinitions] => DTS\eBaySDK\Trading\Types\FeatureDefinitionsType Object
                (
                    [values:DTS\eBaySDK\Types\BaseType:private] => Array
                        (
                            [ListingDurations] => DTS\eBaySDK\Trading\Types\ListingDurationDefinitionsType Object
                                (
                                    [values:DTS\eBaySDK\Types\BaseType:private] => Array
                                        (
                                            [Version] => 3
                                        )

                                    [attachment:DTS\eBaySDK\Types\BaseType:private] => Array
                                        (
                                            [data] => 
                                            [mimeType] => 
                                        )

                                )
```

How would this response tell me that it supports GTC or not ? 

Thanks

**Comment by raheelkhan** [comment]
I added an element in `Trading/Types/GetCategoryFeaturesRequestType::propertyTypes` and it is now showing a detailed information. Please let me know if there is any other way to do this as i do not want to edit the SDK code.

Below is the element i added
```
        'DetailLevel' => array(
            'type' => 'string',
            'unbound' => false,
            'attribute' => false,
            'elementName' => 'DetailLevel' 
        )
```

As per the Ebay documentation :

```
ViewAllNodes	boolean	Optional	You must set DetailLevel to ReturnAll in order to correctly populate the response when you set ViewAllNodes to true. In this case, eBay returns the site defaults along with all the categories that override the feature settings they inherit. Here, each Category container shows only the features that it has overridden from its parent node. 

If you also specify a CategoryID, eBay returns the details for that category, along with containers for each of its child categories that have feature overrides. 

Note that if ViewAllNodes is set to false (the default) and DetailLevel is set to ReturnAll, eBay returns only the leaf categories that have features that override the settings they inherit. In this case, the call will not return leaf categories that do not have overrides.
Default: false.
```

So i had to use ViewAllNodes as true. And when i am using DetailLevel property to set 'ReturnAll`, It was throwing error

`Invalid property type for DetailLevel, expected <outbound>, got <string>`

Looking forward to hear your words.

Thanks

**Comment by davidtsadler** [comment]
You don' need to modify the code as the [GetCategoryFeaturesRequestType](https://github.com/davidtsadler/ebay-sdk-php/blob/master/src/DTS/eBaySDK/Trading/Types/GetCategoryFeaturesRequestType.php#L32) class extends [AbstractRequestType](https://github.com/davidtsadler/ebay-sdk-php/blob/master/src/DTS/eBaySDK/Trading/Types/AbstractRequestType.php#L50) and so will inherit the DetailLevel property.

The [DetailLevel](http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/GetOrders.html#Request.DetailLevel) is a [repeatable](http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/simpleTypes.html#repeatable) field in the API, which just means that you can specify more than one value in the request. The SDK treats repeatable fields as arrays. So the following code are all valid ways of setting the DetailLevel property.

```php
// Assign a single element array.
$request->DetailLevel = ['ReturnAll'];
```

```php
// Assign multiple values in one go.
$request->DetailLevel = ['ReturnAll', 'ReturnHeaders', 'ReturnMessages'];
```


```php
// Assign multiple values one at a time.
$request->DetailLevel[] = 'ReturnAll';
$request->DetailLevel[] = 'ReturnHeaders';
$request->DetailLevel[] = 'ReturnMessages';
```
