### ISSUE TITLE
How to pass DateTime object with ISO8601 Format

### ISSUE THREAD

**Issue by raheelkhan** [davidtsadler/ebay-sdk#18]
```
$request = new Types\GetOrdersRequestType();
$request->CreateTimeFrom = new DateTime($filters['create_time_from']);
``` 
Hi,

Above is the snippet of a function i made to utilize GetOrders method. Ebay requires the date format in ISO8601 Format but when i convert the DateTime to ISO it no more remain an object but string. And this SDK is not allowing to pass date as a string.

Is there any way for achieving this or i have to change the core SDK file again ?

Thanks alot.

**Comment by davidtsadler** [comment]
The SDK automatically converts DateTime objects into the ISO 8601 date and time format when generating the XML.

```php
// Assign a DateTime object to a property.
$request->CreateTimeFrom = new \DateTime('2015-10-01');
```

```xml
<GetOrdersRequest>
	<CreateTimeFrom>2015-10-01T13:00:00.000Z</CreateTimeFrom>
</GetOrdersRequest>
```

The only thing to be aware of is that the SDK will not convert local time to UTC. If you are passing a time value to the SDK you must ensure that is has already been converted to UTC.

```php
$request->CreateTimeFrom = new \DateTime('2015-10-01 13:01', new \DateTimeZone('UTC'));
```

```xml
<GetOrdersRequest>
	<CreateTimeFrom>2015-10-01T13:01:00.000Z</CreateTimeFrom>
</GetOrdersRequest>
```

**Comment by raheelkhan** [comment]
Oh thanks, BTW how do you dump the XML for debugging whats been generated so far ?

**Comment by michabbb** [comment]
same question, what is best practise to get the raw xml right now ? thanks

**Comment by davidtsadler** [comment]
I'll look at writing some documentation over the weekend that will explain how to debug the request and response XML. Before then there is [an example that may help](https://github.com/davidtsadler/ebay-sdk/pull/11#issuecomment-69473610). This is an area of the SDK that I hope to improve with the version 1.0.0 release.

**Comment by davidtsadler** [comment]
There is now a short [guide available for debugging with the SDK](http://devbay.net/sdk/guides/debugging/).

**Comment by michabbb** [comment]
+1 thanks a lot !!

**Comment by raheelkhan** [comment]
Thanks for the tutorial. But what if i just want to see $request or $response individually ? Right now its printing both the XMLs. Thanks

**Comment by davidtsadler** [comment]
Unless I'm missing something obvious you can just adapt the logger example to show either the request or response by removing the code that you aren't interest in. If you can provide more details via the [forum](https://groups.google.com/forum/#!forum/ebay-sdk-php)  on what you are trying to achieve then I *may* be able to give a better answer.

**Comment by shreyanshpanchal** [comment]
Hi David @davidtsadler,

Do i have to create timestamp manually on this call `getOrders`  in `FulfillmentService`?

```
'filter' => [
    'type' => 'string',
    'repeatable' => false,
    'attribute' => false,
    'elementName' => 'filter'
]
```
This expects a string made up of these combination  `creationdate`, `lastmodifieddate`, `orderfulfillmentstatus`
