### ISSUE TITLE
Problems parsing GetStore $xml Response

### ISSUE THREAD

**Issue by web-caos** [davidtsadler/ebay-sdk#21]
Hello,
i know this repo is outdated, but right now i have to make this one work for an old project.
I have a problem getting the Store categories, the returned object show only one category (even if have 300 categories).
I dumped the $xml given to XmlParser->parse() and it look fine with all categories in the right place but at the end of the function the returned object have only one category even if i dump just $this at the end of the function.

Any idea for put me on the right track? :(

**Comment by davidtsadler** [comment]
Do you have some example code? I'll have a look and see what I can do.

**Comment by web-caos** [comment]
Thanks David,
here a piece of code, i just call the GetStore for get the store categories and then store them in a table:
`static function getStoreCategories()
    {

        $service = new Services\TradingService(array(
            'apiVersion' => Config::get('ebay.tradingApiVersion'),
            'siteId' => Constants\SiteIds::IT
        ));

        $request = new Types\GetStoreRequestType();

        $request->RequesterCredentials = new Types\CustomSecurityHeaderType();
        $request->RequesterCredentials->eBayAuthToken = Config::get('ebay.production.userToken');

        $response = $service->getStore($request);

        $errors = array();

        if (isset($response->Errors)) {

            foreach ($response->Errors as $error) {

                $errors[] = array(
                    'Type' => $error->SeverityCode === Enums\SeverityCodeType::C_ERROR ? 'Error' : 'Warning',
                    'ShortMsg' => $error->ShortMessage,
                    'LongMsg' => $error->LongMessage
                );

            }

        }

        if ($response->Ack === 'Failure') {

            $data = array(
                'status' => 'Error',
                'msg' => 'Si sono verificati problemi nella soncronizzazione delle categorie, consulta i log di sistema.',
                'errors' => $errors
            );

            return $data;

        }else{

            //eBayShopCategory::truncate();

            $store = $response->Store;

            foreach ($store->CustomCategories->CustomCategory as $category) {
                $categoryDB = new eBayShopCategory;
                $categoryDB->id = $category->CategoryID;
                $categoryDB->Name = $category->Name;
                $categoryDB->save();

            }

            $data = array(
                'status' => 'Success',
                'msg' => 'Categorie eBay sincronizzate correttamente.',
                'errors' => $errors
            );

            return $data;

        }

    }`

I use this your old sdk for many tasks without any kind of problem, and here is the first time i found a problem.
If i dump the $response i notice i have only one category returned, so i went to take a look around in your code and seems maybe the problem is `here:`

`
public function parse($xml)
    {

/* if here i dump the $xml
var_dump($xml);
i see that the xml is fine and all categories are there*/

        $parser = xml_parser_create('UTF-8');

        xml_parser_set_option($parser, XML_OPTION_CASE_FOLDING, 0);
        xml_parser_set_option($parser, XML_OPTION_SKIP_WHITE, 1);
        xml_set_object($parser, $this);
        xml_set_element_handler($parser, 'startElement', 'endElement');
        xml_set_character_data_handler($parser, 'cdata');

        xml_parse($parser, $xml, true);

        xml_parser_free($parser);

/*if now i dump the object
var_dump($this->rootObject);
everything is fine but the categories are gone and only one is returned, maybe is like if instead to repeat the category elements overwrite them all till the last*/

        return $this->rootObject;
    }
`

same problem with 2 different stores.

**Comment by web-caos** [comment]
Thanks again for the attention David but seem i solved, in StoreCustomCategoryArrayType changed unbound = false to true in the properties and now in this way work, just hope i will not break something else in this way :D

**Comment by davidtsadler** [comment]
Setting unbound to true is correct so don't worry about it breaking :)
