### ISSUE TITLE
Feature: Retry Subscriber

### ISSUE THREAD

**Issue by tmatei** [davidtsadler/ebay-sdk#6]
Could you add the ability to add a retry subscriber to the HttpClient that uses Guzzle? 

https://github.com/guzzle/retry-subscriber

**Comment by michabbb** [comment]
dear @davidtsadler , in the last time we had several problems with the ebay connection, we build a retry for ourself, but working with ebay without any retry-method is not working... so i want to make a new call for this feature here ;) thx!

**Comment by davidtsadler** [comment]
Would adding a method to allow access to the Http client used in the SDK be enough? I'm thinking it should make the following possible.
```
use GuzzleHttp\Subscriber\Retry\RetrySubscriber;

// Retry 500 and 503 responses
$retry = new RetrySubscriber([
    'filter' => RetrySubscriber::createStatusFilter()
]);

$service = new Services\TradingService(...);
$service->client()->getEmitter()->attach($retry);
```

**Comment by michabbb** [comment]
Would this solution be able to handle curl ssl timeouts or "unable to resolve host" problems? Don't know if this goes too deep, but this are real problems we have to deal with...

**Comment by davidtsadler** [comment]
If I provide access to the Guzzle object it should allow you to set the various cURL options. Because the SDK uses [Guzzle 3](http://guzzle3.readthedocs.org/en/latest/http-client/client.html#configuration-options) I think you will be able to do something like the following. (I've haven't tried it)

```
$service->client()->getConfig()->setPath('curl.options', array(
'CURLOPT_TIMEOUT' => 10
));
```

In all honestly I don't know if this will resolve your cURL issues as it's going to be due to your system setup and things such as which version of the cURL lib is currently installed. I will try and upload an example tomorrow that shows how to provide your own HTTP client for the SDK to use as it may provide an alternative solution. I'm also currently in the process of looking to update the SDK so that it uses the latest Guzzle Version 5.

**Comment by michabbb** [comment]
thanks a lot, sound interesting....  because of [this](http://www.sitecrafting.com/blog/php-curl-ssl-connection-timeout/) posting, i would like to test if something changes when using *CURLOPT_FRESH_CONNECT* .... with your changes, this should be possible....

**Comment by davidtsadler** [comment]
The 0.1.4 release no allows access to the Guzzle client object.
```php
$service = new Services\TradingService(array(
  'apiVersion' => 925,
  'siteId' => Constants\SiteIds::US
));

$guzzle = $service->httpClient()->guzzle();

$guzzle->getConfig()->setPath('curl.options', array(
    'CURLOPT_VERBOSE' => 1
));
```

I'm not going to close this issue as the SDK won't be able to support Guzzle's [retry-subscriber](https://github.com/guzzle/retry-subscriber) until I update it to use Guzzle 5 or 6.  Updating the Guzzle version is something that I want to do but there are some other important changes that I need to make to the SDK first. I'll make an announcement in the next few weeks regarding these changes. Once they have been done I can update to the latest version of Guzzle.

**Comment by davidtsadler** [comment]
I've upload an example of how to provide your own [HTTP client](https://github.com/davidtsadler/ebay-sdk-examples/blob/master/misc/01-http-client.php). The example uses cURL but you can use any method that can make a HTTP POST request. It should also be possible to use the latest version of Guzzle if it is installed on your system.

**Comment by michabbb** [comment]
thanks a lot, i will try this and let you know... :+1:

**Comment by michabbb** [comment]
@davidtsadler sorry, i have been too busy ;-(( @tmatei did you try it ???

**Comment by tmatei** [comment]
@michabbb it's been a really long time however I just got to upgrading the service. I'm going to see if that helps and I also added a try catch and an automatic retry in case there's an exception. This has been a really low priority for me, but now that you are able to specify your own http client, its not a big deal to add the retry subscriber.

**Comment by michabbb** [comment]
@tmatei we had not time till now to switch over to davids new sdk, so right now we do the "try catch", too. this works pretty well. i only wanted to ask, i you have been able to collect some experiences with the "own http client" ;-) thanks for you update.
